import { Expense } from '../contexts/FinanceContext';

export const sampleExpenses: Omit<Expense, 'id' | 'createdAt' | 'updatedAt'>[] = [
  {
    title: 'Aluguel',
    amount: 1200.00,
    date: new Date(2024, 0, 5).toISOString(),
    category: 'Moradia',
    description: 'Aluguel do apartamento',
    isRecurring: true,
    recurrenceType: 'monthly',
    installments: 12,
    currentInstallment: 1,
    isFinancing: false,
  },
  {
    title: 'Financiamento Casa',
    amount: 2500.00,
    date: new Date(2024, 0, 10).toISOString(),
    category: 'Financiamento',
    description: 'Financiamento imobiliário Caixa',
    isRecurring: true,
    recurrenceType: 'monthly',
    installments: 360,
    currentInstallment: 24,
    isFinancing: true,
    interestRate: 1.2,
    monthlyAdjustment: 0.5,
  },
  {
    title: 'Supermercado',
    amount: 450.00,
    date: new Date(2024, 0, 15).toISOString(),
    category: 'Alimentação',
    description: 'Compras do mês',
    isRecurring: false,
  },
  {
    title: 'Combustível',
    amount: 200.00,
    date: new Date(2024, 0, 18).toISOString(),
    category: 'Transporte',
    description: 'Abastecimento do carro',
    isRecurring: false,
  },
  {
    title: 'Academia',
    amount: 89.90,
    date: new Date(2024, 0, 20).toISOString(),
    category: 'Saúde',
    description: 'Mensalidade da academia',
    isRecurring: true,
    recurrenceType: 'monthly',
    installments: 12,
    currentInstallment: 1,
    isFinancing: false,
  },
  {
    title: 'Netflix',
    amount: 39.90,
    date: new Date(2024, 0, 25).toISOString(),
    category: 'Lazer',
    description: 'Assinatura Netflix',
    isRecurring: true,
    recurrenceType: 'monthly',
    installments: 12,
    currentInstallment: 1,
    isFinancing: false,
  },
  {
    title: 'Financiamento Carro',
    amount: 800.00,
    date: new Date(2024, 0, 28).toISOString(),
    category: 'Financiamento',
    description: 'Financiamento do carro',
    isRecurring: true,
    recurrenceType: 'monthly',
    installments: 60,
    currentInstallment: 18,
    isFinancing: true,
    interestRate: 1.8,
    monthlyAdjustment: 0.3,
  },
  {
    title: 'Conta de Luz',
    amount: 180.00,
    date: new Date(2024, 1, 5).toISOString(),
    category: 'Moradia',
    description: 'Conta de energia elétrica',
    isRecurring: true,
    recurrenceType: 'monthly',
    installments: 12,
    currentInstallment: 2,
    isFinancing: false,
  },
  {
    title: 'Conta de Água',
    amount: 95.00,
    date: new Date(2024, 1, 8).toISOString(),
    category: 'Moradia',
    description: 'Conta de água',
    isRecurring: true,
    recurrenceType: 'monthly',
    installments: 12,
    currentInstallment: 2,
    isFinancing: false,
  },
  {
    title: 'Internet',
    amount: 129.90,
    date: new Date(2024, 1, 10).toISOString(),
    category: 'Moradia',
    description: 'Plano de internet',
    isRecurring: true,
    recurrenceType: 'monthly',
    installments: 12,
    currentInstallment: 2,
    isFinancing: false,
  },
];

export const getSampleDataForDemo = () => {
  return sampleExpenses.map((expense, index) => ({
    ...expense,
    id: `sample-${index + 1}`,
    createdAt: new Date(2024, 0, 1).toISOString(),
    updatedAt: new Date(2024, 0, 1).toISOString(),
  }));
}; 